name: Install build dependencies
description: Installs dependencies needed for compilation

inputs:
  extra:
    description: Extra dependencies to install
    required: false
    default: ''
runs:
  using: composite
  steps:
  - name: Install dependencies
    run: |-
      apt-get update
      apt-get install \
        -y cmake g++ git libfmt-dev ${{ inputs.extra }}
    shell: bash
